Traceback (most recent call last):
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 650, in async_setup_kernel
    yield
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pynwb import NWBHDF5IO

with NWBHDF5IO(s3_path, mode='r', load_namespaces=True, driver='ros3') as io:
    nwbfile = io.read()
    print(nwbfile)
    print(nwbfile.acquisition['lick_times'].time_series['lick_left_times'].data[:])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpynwb[39;00m [38;5;28;01mimport[39;00m NWBHDF5IO
[0;32m----> 3[0m [38;5;28;01mwith[39;00m [43mNWBHDF5IO[49m[43m([49m[43ms3_path[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mload_namespaces[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mdriver[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mros3[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m io:
[1;32m      4[0m     nwbfile [38;5;241m=[39m io[38;5;241m.[39mread()
[1;32m      5[0m     [38;5;28mprint[39m(nwbfile)

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/utils.py:645[0m, in [0;36mdocval.<locals>.dec.<locals>.func_call[0;34m(*args, **kwargs)[0m
[1;32m    643[0m [38;5;28;01mdef[39;00m [38;5;21mfunc_call[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    644[0m     pargs [38;5;241m=[39m _check_args(args, kwargs)
[0;32m--> 645[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43margs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mpargs[49m[43m)[49m

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/pynwb/__init__.py:233[0m, in [0;36mNWBHDF5IO.__init__[0;34m(self, **kwargs)[0m
[1;32m    230[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mcannot load namespaces from file when writing to it[39m[38;5;124m"[39m)
[1;32m    232[0m     tm [38;5;241m=[39m get_type_map()
[0;32m--> 233[0m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mload_namespaces[49m[43m([49m[43mtm[49m[43m,[49m[43m [49m[43mpath[49m[43m,[49m[43m [49m[43mfile[49m[38;5;241;43m=[39;49m[43mfile_obj[49m[43m,[49m[43m [49m[43mdriver[49m[38;5;241;43m=[39;49m[43mdriver[49m[43m)[49m
[1;32m    234[0m     manager [38;5;241m=[39m BuildManager(tm)
[1;32m    236[0m     [38;5;66;03m# XXX: Leaving this here in case we want to revert to this strategy for[39;00m
[1;32m    237[0m     [38;5;66;03m#      loading cached namespaces[39;00m
[1;32m    238[0m     [38;5;66;03m# ns_catalog = NamespaceCatalog(NWBGroupSpec, NWBDatasetSpec, NWBNamespace)[39;00m
[0;32m   (...)[0m
[1;32m    241[0m     [38;5;66;03m# tm.copy_mappers(get_type_map())[39;00m
[1;32m    242[0m [38;5;28;01melse[39;00m:

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/utils.py:645[0m, in [0;36mdocval.<locals>.dec.<locals>.func_call[0;34m(*args, **kwargs)[0m
[1;32m    643[0m [38;5;28;01mdef[39;00m [38;5;21mfunc_call[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    644[0m     pargs [38;5;241m=[39m _check_args(args, kwargs)
[0;32m--> 645[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43margs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mpargs[49m[43m)[49m

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/backends/hdf5/h5tools.py:149[0m, in [0;36mHDF5IO.load_namespaces[0;34m(cls, **kwargs)[0m
[1;32m    138[0m [38;5;250m[39m[38;5;124;03m"""Load cached namespaces from a file.[39;00m
[1;32m    139[0m 
[1;32m    140[0m [38;5;124;03mIf `file` is not supplied, then an :py:class:`h5py.File` object will be opened for the given `path`, the[39;00m
[0;32m   (...)[0m
[1;32m    144[0m [38;5;124;03m:raises ValueError: if both `path` and `file` are supplied but `path` is not the same as the path of `file`.[39;00m
[1;32m    145[0m [38;5;124;03m"""[39;00m
[1;32m    146[0m namespace_catalog, path, namespaces, file_obj, driver [38;5;241m=[39m popargs(
[1;32m    147[0m     [38;5;124m'[39m[38;5;124mnamespace_catalog[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mpath[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mnamespaces[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mfile[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdriver[39m[38;5;124m'[39m, kwargs)
[0;32m--> 149[0m open_file_obj [38;5;241m=[39m [38;5;28;43mcls[39;49m[38;5;241;43m.[39;49m[43m__resolve_file_obj[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mfile_obj[49m[43m,[49m[43m [49m[43mdriver[49m[43m)[49m
[1;32m    150[0m [38;5;28;01mif[39;00m file_obj [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:  [38;5;66;03m# need to close the file object that we just opened[39;00m
[1;32m    151[0m     [38;5;28;01mwith[39;00m open_file_obj:

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/backends/hdf5/h5tools.py:124[0m, in [0;36mHDF5IO.__resolve_file_obj[0;34m(cls, path, file_obj, driver)[0m
[1;32m    122[0m     [38;5;28;01mif[39;00m driver [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    123[0m         file_kwargs[38;5;241m.[39mupdate(driver[38;5;241m=[39mdriver)
[0;32m--> 124[0m     file_obj [38;5;241m=[39m [43mFile[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mfile_kwargs[49m[43m)[49m
[1;32m    125[0m [38;5;28;01mreturn[39;00m file_obj

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/h5py/_hl/files.py:518[0m, in [0;36mFile.__init__[0;34m(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, meta_block_size, **kwds)[0m
[1;32m    515[0m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m: S3 location must begin with [39m[38;5;124m'[39m
[1;32m    516[0m                              [38;5;124m'[39m[38;5;124meither [39m[38;5;124m"[39m[38;5;124mhttps://[39m[38;5;124m"[39m[38;5;124m, [39m[38;5;124m"[39m[38;5;124mhttp://[39m[38;5;124m"[39m[38;5;124m, or [39m[38;5;124m"[39m[38;5;124ms3://[39m[38;5;124m"[39m[38;5;124m'[39m)
[1;32m    517[0m     [38;5;28;01melse[39;00m:
[0;32m--> 518[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    519[0m             [38;5;124m"[39m[38;5;124mh5py was built without ROS3 support, can[39m[38;5;124m'[39m[38;5;124mt use ros3 driver[39m[38;5;124m"[39m)
[1;32m    521[0m [38;5;28;01mif[39;00m locking [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m hdf5_version [38;5;241m<[39m ([38;5;241m1[39m, [38;5;241m12[39m, [38;5;241m1[39m) [38;5;129;01mand[39;00m (
[1;32m    522[0m         hdf5_version[:[38;5;241m2[39m] [38;5;241m!=[39m ([38;5;241m1[39m, [38;5;241m10[39m) [38;5;129;01mor[39;00m hdf5_version[[38;5;241m2[39m] [38;5;241m<[39m [38;5;241m7[39m):
[1;32m    523[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mHDF5 version >= 1.12.1 or 1.10.x >= 1.10.7 required for file locking options.[39m[38;5;124m"[39m)

[0;31mValueError[0m: h5py was built without ROS3 support, can't use ros3 driver

