Traceback (most recent call last):
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 650, in async_setup_kernel
    yield
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ashley/anaconda3/envs/jb/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# set the filename
filename = '000006/sub-anm369962/sub-anm369962_ses-20170310.nwb'

# assign file as an NWBHDF5IO object
io = NWBHDF5IO(filename, 'r')

# read the file
nwb_file = io.read()

nwb_file
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      2[0m filename [38;5;241m=[39m [38;5;124m'[39m[38;5;124m000006/sub-anm369962/sub-anm369962_ses-20170310.nwb[39m[38;5;124m'[39m
[1;32m      4[0m [38;5;66;03m# assign file as an NWBHDF5IO object[39;00m
[0;32m----> 5[0m io [38;5;241m=[39m [43mNWBHDF5IO[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      7[0m [38;5;66;03m# read the file[39;00m
[1;32m      8[0m nwb_file [38;5;241m=[39m io[38;5;241m.[39mread()

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/utils.py:668[0m, in [0;36mdocval.<locals>.dec.<locals>.func_call[0;34m(*args, **kwargs)[0m
[1;32m    666[0m [38;5;28;01mdef[39;00m [38;5;21mfunc_call[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    667[0m     pargs [38;5;241m=[39m _check_args(args, kwargs)
[0;32m--> 668[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43margs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mpargs[49m[43m)[49m

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/pynwb/__init__.py:300[0m, in [0;36mNWBHDF5IO.__init__[0;34m(self, **kwargs)[0m
[1;32m    298[0m [38;5;28;01mif[39;00m load_namespaces:
[1;32m    299[0m     tm [38;5;241m=[39m get_type_map()
[0;32m--> 300[0m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mload_namespaces[49m[43m([49m[43mtm[49m[43m,[49m[43m [49m[43mpath[49m[43m,[49m[43m [49m[43mfile[49m[38;5;241;43m=[39;49m[43mfile_obj[49m[43m,[49m[43m [49m[43mdriver[49m[38;5;241;43m=[39;49m[43mdriver[49m[43m,[49m[43m [49m[43maws_region[49m[38;5;241;43m=[39;49m[43maws_region[49m[43m)[49m
[1;32m    301[0m     manager [38;5;241m=[39m BuildManager(tm)
[1;32m    303[0m     [38;5;66;03m# XXX: Leaving this here in case we want to revert to this strategy for[39;00m
[1;32m    304[0m     [38;5;66;03m#      loading cached namespaces[39;00m
[1;32m    305[0m     [38;5;66;03m# ns_catalog = NamespaceCatalog(NWBGroupSpec, NWBDatasetSpec, NWBNamespace)[39;00m
[0;32m   (...)[0m
[1;32m    308[0m     [38;5;66;03m# tm.copy_mappers(get_type_map())[39;00m
[1;32m    309[0m [38;5;28;01melse[39;00m:

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/utils.py:668[0m, in [0;36mdocval.<locals>.dec.<locals>.func_call[0;34m(*args, **kwargs)[0m
[1;32m    666[0m [38;5;28;01mdef[39;00m [38;5;21mfunc_call[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    667[0m     pargs [38;5;241m=[39m _check_args(args, kwargs)
[0;32m--> 668[0m     [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43margs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mpargs[49m[43m)[49m

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/backends/hdf5/h5tools.py:185[0m, in [0;36mHDF5IO.load_namespaces[0;34m(cls, **kwargs)[0m
[1;32m    174[0m [38;5;250m[39m[38;5;124;03m"""Load cached namespaces from a file.[39;00m
[1;32m    175[0m 
[1;32m    176[0m [38;5;124;03mIf `file` is not supplied, then an :py:class:`h5py.File` object will be opened for the given `path`, the[39;00m
[0;32m   (...)[0m
[1;32m    180[0m [38;5;124;03m:raises ValueError: if both `path` and `file` are supplied but `path` is not the same as the path of `file`.[39;00m
[1;32m    181[0m [38;5;124;03m"""[39;00m
[1;32m    182[0m namespace_catalog, path, namespaces, file_obj, driver, aws_region [38;5;241m=[39m popargs(
[1;32m    183[0m     [38;5;124m'[39m[38;5;124mnamespace_catalog[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mpath[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mnamespaces[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mfile[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdriver[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124maws_region[39m[38;5;124m'[39m, kwargs)
[0;32m--> 185[0m open_file_obj [38;5;241m=[39m [38;5;28;43mcls[39;49m[38;5;241;43m.[39;49m[43m__resolve_file_obj[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mfile_obj[49m[43m,[49m[43m [49m[43mdriver[49m[43m,[49m[43m [49m[43maws_region[49m[38;5;241;43m=[39;49m[43maws_region[49m[43m)[49m
[1;32m    186[0m [38;5;28;01mif[39;00m file_obj [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:  [38;5;66;03m# need to close the file object that we just opened[39;00m
[1;32m    187[0m     [38;5;28;01mwith[39;00m open_file_obj:

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/hdmf/backends/hdf5/h5tools.py:158[0m, in [0;36mHDF5IO.__resolve_file_obj[0;34m(cls, path, file_obj, driver, aws_region)[0m
[1;32m    156[0m         [38;5;28;01mif[39;00m aws_region [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    157[0m             file_kwargs[38;5;241m.[39mupdate(aws_region[38;5;241m=[39m[38;5;28mbytes[39m(aws_region, [38;5;124m"[39m[38;5;124mascii[39m[38;5;124m"[39m))
[0;32m--> 158[0m     file_obj [38;5;241m=[39m [43mFile[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mfile_kwargs[49m[43m)[49m
[1;32m    159[0m [38;5;28;01mreturn[39;00m file_obj

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/h5py/_hl/files.py:567[0m, in [0;36mFile.__init__[0;34m(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, meta_block_size, **kwds)[0m
[1;32m    558[0m     fapl [38;5;241m=[39m make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
[1;32m    559[0m                      locking, page_buf_size, min_meta_keep, min_raw_keep,
[1;32m    560[0m                      alignment_threshold[38;5;241m=[39malignment_threshold,
[1;32m    561[0m                      alignment_interval[38;5;241m=[39malignment_interval,
[1;32m    562[0m                      meta_block_size[38;5;241m=[39mmeta_block_size,
[1;32m    563[0m                      [38;5;241m*[39m[38;5;241m*[39mkwds)
[1;32m    564[0m     fcpl [38;5;241m=[39m make_fcpl(track_order[38;5;241m=[39mtrack_order, fs_strategy[38;5;241m=[39mfs_strategy,
[1;32m    565[0m                      fs_persist[38;5;241m=[39mfs_persist, fs_threshold[38;5;241m=[39mfs_threshold,
[1;32m    566[0m                      fs_page_size[38;5;241m=[39mfs_page_size)
[0;32m--> 567[0m     fid [38;5;241m=[39m [43mmake_fid[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43muserblock_size[49m[43m,[49m[43m [49m[43mfapl[49m[43m,[49m[43m [49m[43mfcpl[49m[43m,[49m[43m [49m[43mswmr[49m[38;5;241;43m=[39;49m[43mswmr[49m[43m)[49m
[1;32m    569[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(libver, [38;5;28mtuple[39m):
[1;32m    570[0m     [38;5;28mself[39m[38;5;241m.[39m_libver [38;5;241m=[39m libver

File [0;32m~/anaconda3/envs/jb/lib/python3.11/site-packages/h5py/_hl/files.py:231[0m, in [0;36mmake_fid[0;34m(name, mode, userblock_size, fapl, fcpl, swmr)[0m
[1;32m    229[0m     [38;5;28;01mif[39;00m swmr [38;5;129;01mand[39;00m swmr_support:
[1;32m    230[0m         flags [38;5;241m|[39m[38;5;241m=[39m h5f[38;5;241m.[39mACC_SWMR_READ
[0;32m--> 231[0m     fid [38;5;241m=[39m [43mh5f[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mflags[49m[43m,[49m[43m [49m[43mfapl[49m[38;5;241;43m=[39;49m[43mfapl[49m[43m)[49m
[1;32m    232[0m [38;5;28;01melif[39;00m mode [38;5;241m==[39m [38;5;124m'[39m[38;5;124mr+[39m[38;5;124m'[39m:
[1;32m    233[0m     fid [38;5;241m=[39m h5f[38;5;241m.[39mopen(name, h5f[38;5;241m.[39mACC_RDWR, fapl[38;5;241m=[39mfapl)

File [0;32mh5py/_objects.pyx:54[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/_objects.pyx:55[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/h5f.pyx:106[0m, in [0;36mh5py.h5f.open[0;34m()[0m

[0;31mFileNotFoundError[0m: [Errno 2] Unable to open file (unable to open file: name = '000006/sub-anm369962/sub-anm369962_ses-20170310.nwb', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

