Traceback (most recent call last):
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ashley/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pynwb import NWBHDF5IO

with NWBHDF5IO(s3_path, mode='r', load_namespaces=True, driver='ros3') as io:
    nwbfile = io.read()
    print(nwbfile.acquisition['ElectricalSeries'].data.shape)
    sampling_freq = nwbfile.acquisition['ElectricalSeries'].rate # get the sampling frequency in Hz
    ephys_data = (nwbfile.acquisition['ElectricalSeries'].data[:3000000, 99])*nwbfile.acquisition['ElectricalSeries'].conversion
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-4a0fb7d19a4f>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0mpynwb[0m [0;32mimport[0m [0mNWBHDF5IO[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mwith[0m [0mNWBHDF5IO[0m[0;34m([0m[0ms3_path[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;34m'r'[0m[0;34m,[0m [0mload_namespaces[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0mdriver[0m[0;34m=[0m[0;34m'ros3'[0m[0;34m)[0m [0;32mas[0m [0mio[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m     [0mnwbfile[0m [0;34m=[0m [0mio[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mprint[0m[0;34m([0m[0mnwbfile[0m[0;34m.[0m[0macquisition[0m[0;34m[[0m[0;34m'ElectricalSeries'[0m[0;34m][0m[0;34m.[0m[0mdata[0m[0;34m.[0m[0mshape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py[0m in [0;36mfunc_call[0;34m(*args, **kwargs)[0m
[1;32m    577[0m         [0;32mif[0m [0mis_method[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    578[0m             [0;32mdef[0m [0mfunc_call[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 579[0;31m                 [0mpargs[0m [0;34m=[0m [0m_check_args[0m[0;34m([0m[0margs[0m[0;34m,[0m [0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    580[0m                 [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0;34m**[0m[0mpargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    581[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py[0m in [0;36m_check_args[0;34m(args, kwargs)[0m
[1;32m    570[0m                 [0;32mif[0m [0mparse_err[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    571[0m                     [0mmsg[0m [0;34m=[0m [0;34m'%s: %s'[0m [0;34m%[0m [0;34m([0m[0mfunc[0m[0;34m.[0m[0m__qualname__[0m[0;34m,[0m [0;34m', '[0m[0;34m.[0m[0mjoin[0m[0;34m([0m[0mparse_err[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 572[0;31m                     [0;32mraise[0m [0mExceptionType[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    573[0m [0;34m[0m[0m
[1;32m    574[0m             [0;32mreturn[0m [0mparsed[0m[0;34m[[0m[0;34m'args'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: NWBHDF5IO.__init__: unrecognized argument: 'driver'
TypeError: NWBHDF5IO.__init__: unrecognized argument: 'driver'

